# -*- coding: utf-8 -*-
"""Simple CalculatorAHAD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ErvB26ztrju57GNoArbB0NCiz0XkGG04
"""

def add(x, y):
    return x + y


def subtract(x, y):
    return x - y


def divide(x, y):
    return x / y


def multiply(x, y):
     return x * y


def square(x):
    return x ** 2



def power(x, y):
    return x ** y


def sqrt(x):
    return x ** 0.5